USERID --  아이디
USERPW -- 패스워드
USERNAME -- 이름
GENDER -- 성
REGNUM -- 주민번호
USERACCOUNT -- 주소
REGDATE -- 날짜

CREATE TABLE USER_TBL
(
    USERID      VARCHAR2(20)    PRIMARY KEY,
    USERPW      VARCHAR2(20)    NOT NULL,
    USERNAME    VARCHAR2(20)    NOT NULL,
    GENDER      VARCHAR2(6)     NOT NULL,
    REGNUM      VARCHAR2(50)    NOT NULL,
    USERACCOUNT VARCHAR2(200)   NOT NULL,
    REGDATE     DATE            DEFAULT SYSDATE
);

INSERT INTO USER_TBL( USERID, USERPW, USERNAME, GENDER, REGNUM, USERACCOUNT)
VALUES( 'MR.hong', '1234', '홍길동', '남', '111111-1111111', '부산시 부산진구 부전동 그린빌라');
commit;